---

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install group packages
  dnf: name={{item}} state=installed
  with_items:
  - "@development tools"
  - "@fedora-packager"
  - "@virtualization"

- name: Install extra packages
  dnf: name={{ item }} state=installed
  with_items:
  - acpi
  - aide
  - android-tools
  - ansible-lint
  - appliance-tools
  - arpwatch
  - asciidoc
  - asciidoc-doc
  - aspell
  - aspell-en
# - atomic
  - autoconf
  - autofs
  - automake
  - awscli
  - binwalk
  - bpython
  - cmake
  - collectl
  - conntrack-tools
  - copr-cli
  - createrepo
  - createrepo_c-devel
#  - crypto-utils
  - Cython
  - dcfldd
  - ditaa
  - dnf-plugins-extras-common
  - dnf-plugins-extras-kickstart
  - dnf-plugins-extras-repoclosure
  - dnf-plugins-extras-repograph
  - dnf-plugins-extras-show-leaves
  - dnf-plugins-extras-tracer
  - docker
  - docker-vim
  - doge
  - doxygen
  - dstat
  - duplicity
  - elixir
  - euca2ools
  - fail2ban
  - fdupes
  - fedfind
  - fedpkg
  - feh
  - figlet
  - firewalld
  - flatpak-builder
  - fwsnort
#  - fwupdate
  - gcc-c++
  - gcc-go
  - gdb-doc
  - gimp
  - glances
#  - gnome-shell-extension-fedmsg
  - gnome-shell-extension-pomodoro
  - gnome-tweak-tool
  - gpaste
  - groovy
  - heimdall
  - hovercraft
  - htop
  - httpie
  - hub
  - imagefactory
  - imagefactory-plugins-Docker
  - imagefactory-plugins-IndirectionCloud
  - inkscape
  - inotify-tools
  - intltool
  - inxi
  - iotop
  - iptraf-ng
  - jq
  - jython
  - kernel-devel
  - kismet
  - kismet-plugins
  - letsencrypt
  - lftp
  - libguestfs
  - libguestfs-tools
  - libguestfs-tools-c
  - libguestfs-xfs
  - libicns-utils
  - libmtp-examples
  - libnfs
  - libnfsidmap
  - libsemanage-devel
  - libtaskotron
  - libtool
  - libvirt
#  - libvirt-python
  - libvirt-sandbox
  - livecd-tools
  - liveusb-creator
  - lm_sensors
  - lorax
  - lshw
  - lsscsi
  - ltrace
  - lynx
#  - mash
  - meld
  - mysql-devel
  - ncftp
  - nfs-utils
  - ngrep
  - nmap
  - nmon
  - nodejs
  - nodejs-docs
  - nodejs-grunt
  - npm
  - openscap
  - openscap-containers
  - openscap-daemon
  - openscap-scanner
  - openscap-utils
  - openssl-devel
  - pandoc
  - pass
  - patchutils
  - pavucontrol
  - pavumeter
  - pcp
  - pcp-doc
  - pcp-gui
  - perf
  - picocom
  - pinta
#  - pkgwat
#  - policycoreutils-python
  - postfix
  - postgresql-devel
  - powertop
  - psad
  - pssh
  - pungi
  - pv
  - pyflakes
  - pykickstart
  - pylint
  - pyp2rpm
  - pypy
  - pyside-tools
  - pytest
  - python3-firewall
  - python-argcomplete
  - python-autopep8
  - python-beautifulsoup4
#  - python-boto
  - python-bottle
  - python-celery
  - python-cffi-doc
#  - python-clientform
  - python-createrepo_c
  - python-demjson
#  - python-docker-py
  - python-docs
#  - python-docs-info
  - python-epdb
  - python-flake8
  - python-flask
  - python-flexmock
  - python-ipython
  - python-ipython-gui
  - python-ipython-sphinx
#  - python-kickstart
  - python-lxml
  - python-mccabe
  - python-mechanize
  - python-mock
  - python-netaddr
  - python-pandas
  - python-passlib
  - python-pep8
#  - python-productmd
  - python-pygments
  - python-pyside
  - python-requests
  - python-rope
#  - python-ropemode
  - python-rpmfluff
  - python-sphinx
  - python-sphinx-doc
  - python-sphinx_rtd_theme
#  - python-straight-plugin
  - python-virtualenv
  - python-virtualenvwrapper
  - python2-devel
  - python3-autopep8
  - python3-bottle
  - python3-bpython
  - python3-celery
  - python3-cffi
  - python3-click
  - python3-Cython
  - python3-devel
  - python3-django
  - python3-docs
  - python3-flake8
  - python3-flask
  - python3-flexmock
  - python3-ipython
  - python3-ipython-gui
  - python3-ipython-sphinx
  - python3-mccabe
  - python3-mock
  - python3-mypy
  - python3-nose
  - python3-pandas
  - python3-pelican
  - python3-pep8
  - python3-pillow-devel
  - python3-productmd
  - python3-pyflakes
  - python3-pygments
  - python3-pylint
  - python3-sphinx
  - python3-sphinx_rtd_theme
  - python3-straight-plugin
  - python3-virtualenv
  - qiv
  - qpdf
  - ranger
  - recode
  - redis
  - rfkill
#  - rolekit
  - rpm-ostree
#  - rpm-ostree-toolbox
  - ruby
  - ruby-devel
  - ruby-doc
  - ruby-irb
#  - rubygem-aws-sdk
  - rubygem-cucumber
#  - rubygem-dynect_rest
#  - rubygem-fog
#  - rubygem-fog-doc
  - rubygem-gem2rpm
  - rubygem-gherkin
  - rubygem-highline
  - rubygem-parseconfig
  - rubygem-pry
  - rubygem-pry-doc
#  - rubygem-puppet-lint
  - rubygem-rails
#  - rubygem-rhc
  - rubygem-rspec
  - rubygem-thor
  - rubygem-wirb
  - rubygems
  - rubygems-devel
  - runc
  - sbcl
#  - sbt
  - scala
  - scap-workbench
  - scapy
  - scl-utils-build
  - screen
  - screen
  - screenfetch
  - setools-console
  - sg3_utils
#  - sigul
  - smartmontools
  - socat
  - spec2scl
  - speedtest-cli
  - spin-kickstarts
  - sssd-nfs-idmap
  - strace
  - surl
  - swig
  - swig-doc
  - sysstat
  - system-storage-manager
  - task
  - tcllib
  - terminator
  - testcloud
  - testdisk
  - thunderbird
  - tito
  - tlp
  - tlp-rdw
  - tmux
  - tmuxinator
  - tpp
  - transmission-cli
  - tuna
  - tuned
  - tuned-utils
  - tuned-utils-systemtap
#  - tunir
  - units
  - vagrant
  - vagrant-doc
  - vagrant-libvirt
  - vagrant-libvirt-doc
  - valgrind
  - vim-enhanced
  - virt-top
  - whois
  - wireshark-cli
  - xbacklight
 # - xchat
  - xclip
  - xfsdump
  - xournal
  - xsel
  - ykclient
  - ykpers

- name: Install RPM packager packages
  dnf: name={{ item }} state=installed
  with_items:
  - blender-rpm-macros
  - erlang-rpm-macros
  - fedmsg
  - fedora-review
  - fedora-review-tests
  - firewalld-filesystem
  - ghc-rpm-macros
  - ghc-rpm-macros-extra
  - ghc-srpm-macros
  - gnat-srpm-macros
  - go-srpm-macros
#  - gofed
#  - gofed-build
#  - gofed-scan
  - golang
  - golang-godoc
  - golang-gotype
  - gotags
  - kernel-rpm-macros
  - kf5-rpm-macros
  - mock
  - nodejs-packaging
  - ocaml-srpm-macros
  - perl-macros
  - perl-srpm-macros
  - python-fedmsg-meta-fedora-infrastructure
  - python-macros
  - rpm-apidocs
  - rpm-build
  - rpm-devel
  - rpmconf
  - rpmconf
  - rpmdevtools
  - rpmgrill
  - rpmlint
  - rpmorphan
  - rpmreaper
  - scl-utils-build
  - sip-macros
  - terminator
  - web-assets-devel
  when: install_packager

- name: Install extra fonts
  dnf: name={{ item }} state=installed
  with_items:
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts
  when: install_extra_fonts
